site_name: 'Tengen-AI Documentation'

nav:
  - Home: 'index.md'
  - User Guide:
      - Introduction: 'user-guide/introduction.md'
      - Getting Started: 'user-guide/getting-started.md'
      - Usage: 'user-guide/usage.md'
  - API Reference: 'api-reference.md'
  - FAQ: 'faq.md'
  - Contact: 'contact.md'

plugins:
  - search
  - techdocs-core

theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'cyan'

repo_url: 'https://github.com/porasm1998/Tengen-AI/'
edit_uri: 'edit/backstage-integration/'

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true

extra:
  social:
    - type: 'github'
      link: 'https://github.com/porasm1998/Tengen-AI/'
